* Description

  This set of Basho Bench drivers is intended to present a consistent
  set of operations so the same config can be used with all drivers.

* Preload

  A preload driver and config are included which will produce sample
  data accessible via both the HTTP and PBC interfaces.

  ./basho_bench configs/preload.config

** Lorem Ipsum Value Generator

   A lorem ipsum value generator is provided to produce random lorem
   ipsum text. This text can be retrieved from Riak via both HTTP and
   PBC via GET and MapReduce operations.

   This generator was created because of issues retrieving objects
   with random binary data via MapReduce.

* Consistency

  To allow the re-use of a config across several drivers a consistent
  set of config options must be used.

  Options:
  - http - list of urls (may contain https)
  - pb - list of ips and ports
  - raw_name - "riak"
  - mapred_name - "mapred"
  - bucket - <<"test">>
  - link_walk_bucket - <<"link">>
  - link_walk_tag - <<"_">>
  - r - 2
  - w - 2
  - dw - 2
  - rw - 2

  Operations:
  - create
  - read
  - update
  - delete
  - link_walk

  Configs:
  - 80/20 read/write split, pareto key distribution
  - 80/20 read/write split, uniform key distribution
  - link walking

  The goal is to have a limited set of config files that can be used
  for several drivers.

  Drivers:
  - riak_erlang_client
  - riak_java_client
  - riak_python_client
  - riak_ruby_client
  - riak_php_client
